[package]
name = "kube-saver"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version= "0.1.32",features = ["log"]}
tokio = { version = "1.18.2", features = ["full"] }
kube = { version = "0.73.0", features = ["runtime", "derive"] }
kube-derive = "0.73.0" # Support for Custom Resource Definitions
kube-runtime = "0.73.0" # Custom controller support
k8s-openapi = { version = "0.15.0", features = ["v1_24"] }
futures = "~0.3"
# All serde dependencies are used to serialize/deserialize CRDs and other Kubernetes-related structs
serde = "~1.0"
serde_json = "~1.0"
serde_yaml = "0.8.24"
schemars = "~0.8"
thiserror = "~1.0" # Custom Error definitions and convenient error mappings
tracing-subscriber = { version = "0.3.11", features = ["json", "env-filter"] }
yaml-rust = "0.4.5"
jmespath =  { version = "0.3.0", features = ["sync"] }
regex = "1.5.5"
chrono-tz = "0.6"
async-trait = "0.1.53"
env_logger = "0.9.0"
clap = { version = "3.1.18", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }
openssl-src = "300.0.6"

[dev-dependencies]
pretty_assertions = "1"
