apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install.yaml
  - rbac.yaml

configMapGenerator:
  - name: rules
    namespace: kuber
    behavior: create
    files:
      - rules.yaml
