apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install.yaml
  - rbac.yaml
  - namespace.yaml

configMapGenerator:
  - name: rules
    namespace: kube-saver
    behavior: create
    files:
      - rules.yaml
