apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-saver
  namespace: kube-saver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-saver
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups:
      - "*"
    resources:
      - "upscalers"
    verbs:
      - get
      - watch
      - list
      - patch
      - delete
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-saver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-saver
subjects:
  - kind: ServiceAccount
    name: kube-saver
    # change the namespace name below if you want to deploy to a different namespace
    namespace: kube-saver
