rules:
  # scale down deployment with name go-app-deployment-2 when current time/day not in uptime
  - id: rules-downscale-deployments
    uptime: Mon-Fri 09:00-17:00 Australia/Sydney
    # https://jmespath.org/
    jmespath: "metadata.name == 'go-app-deployment'"
    resource:
      - Deployment # type of resource (case sensitive)
    replicas: 0 # either set the replicas:0 or any number during nonuptime
  # scale down all statefulset with name web when current time/day not in uptime
  - id: rules-downscale-statefulset
    uptime: Mon-Fri 09:00-17:00 Australia/Sydney
    jmespath: "metadata.name == 'web'"
    resource:
      - StatefulSet # type of resource (case sensitive)
    replicas: 0 # either set the replicas:0 or any number during nonuptime
  # scale down all deployment & statefulset in namespace kuber when current time/day not in uptime
  - id: rules-downscale-all-in-namespace
    uptime: Mon-Fri 09:00-17:00 Australia/Sydney
    jmespath: "metadata.name == 'kuber'"
    resource:
      - Namespace # type of resource (case sensitive)
    replicas: 0 # either set the replicas:0 or any number during nonuptime
