rules:
  - id: rules-downscale-go-app
    uptime: Mon-Sun 01:05-01:15 Australia/Sydney
    jmespath: "metadata.labels.app == 'go-app'"
    resource:
      - Deployment
      - StatefulSet
    replicas: 0
