apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kuber
  name: go-app-deployment
  labels:
    app: go-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: maheshrayas/goapp:1.0
          ports:
            - containerPort: 8090
