apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: upscalers.kubesaver.com
spec:
  group: kubesaver.com
  names:
    categories: []
    kind: Upscaler
    plural: upscalers
    shortNames: []
    singular: upscaler
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: Upscale scaled downed resources
        properties:
          spec:
            properties:
              scale:
                items:
                  properties:
                    jmespath:
                      type: string
                    replicas:
                      format: int32
                      nullable: true
                      type: integer
                      description: Non mandatory, if not defined, the Controller will upscale to the number of replicas before scaled down replicas
                    resource:
                      items:
                        type: string
                      type: array
                      description:
                          Supported resources -  Namespace, Deployment, Statefulset, Cronjob, hpa.
                          if resources is defined as Namespace, the Custom resource will look for Deployment, Statefulset, Cronjob, hpa
                          defined in the jmespath
                  required:
                  - jmespath
                  - resource
                  type: object
                type: array
            required:
            - scale
            type: object
        required:
        - spec
        title: Upscaler
        type: object
    served: true
    storage: true
    subresources: {}
