apiVersion: kubesaver.com/v1
kind: Upscaler # Identifier of the resource type.
metadata:
  name: upscaler-dep1
spec:
  scale:
  - resource: Deployment
    replicas: 5
    tags:
      metadata.labels.app: "go-app"
