name: Build and push Docker images
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/kube-saver

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build and push
        run: |
          PACKAGE_VERSION=${{ steps.get_version.outputs.VERSION }}
          KUBE_SAVER_IMAGE=$DOCKER_REPO:$PACKAGE_VERSION
          KUBE_SAVER_IMAGE_LATEST=$DOCKER_REPO:latest
          docker buildx build \
            --tag $KUBE_SAVER_IMAGE \
            --tag $KUBE_SAVER_IMAGE_LATEST \
            --platform linux/amd64 \
            --push \
            -f ./Dockerfile .

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Deploy Image to
        run: |
          kubectl apply -f tests/data
          kubectl apply -k k8/

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: cluster
